<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BA-000235932" name="com.telus.wnp.tests.Sanity" tests="1" failures="1" timestamp="2022-05-24T21:03:46 IST" time="27.472" errors="0">
  <testcase name="testMethod_uReportTest" time="27.472" classname="com.telus.wnp.tests.Sanity">
    <failure type="java.lang.AssertionError" message="java.lang.AssertionError: Subscriber status is not as expected expected [active] but found [cancelled]">
      <![CDATA[java.lang.AssertionError: java.lang.AssertionError: Subscriber status is not as expected expected [active] but found [cancelled]
at com.test.ui.actions.Validate.assertEquals(Validate.java:1228)
at com.telus.wnp.steps.SmartDesktopSearchPageSteps.verifySubscriberStatusFromSD(SmartDesktopSearchPageSteps.java:69)
at com.telus.wnp.tests.Sanity.testMethod_uReportTest(Sanity.java:112)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.AssertionError: Subscriber status is not as expected expected [active] but found [cancelled]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertEqualsImpl(Assert.java:140)
at org.testng.Assert.assertEquals(Assert.java:122)
at org.testng.Assert.assertEquals(Assert.java:629)
at com.test.ui.actions.Validate.assertEquals(Validate.java:1224)
... 17 more
]]>
    </failure>
  </testcase> <!-- testMethod_uReportTest -->
  <system-out/>
</testsuite> <!-- com.telus.wnp.tests.Sanity -->
